# Generated by Django 5.0.6 on 2024-06-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_user_email_alter_user_id_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.URLField(blank=True, max_length=248),
        ),
    ]
